USE [master]
GO
/****** Object:  Database [aspnet-b-school-20230612023455]    Script Date: 10/5/2020 9:34:10 PM ******/
/******CREATE DATABASE [aspnet-b-school-20230612023455] ******/

USE [aspnet-b-school-20230612023455]
GO
/****** Object:  Table [dbo].[professeur]    Script Date: 10/06/2023 9:34:11 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[uE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Titre] [nvarchar](50) NOT NULL,
	[Periode] [nvarchar](50) NOT NULL,
	[Etcs] [int] NOT NULL,
	
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
CREATE TABLE [dbo].[sessionUE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Periode] [nvarchar](50) NOT NULL,
	[Lieu] [nvarchar](50) NOT NULL,
	[Etcs] [int] NOT NULL,
	[DateDebut] [date] NOT NULL,
	[DateFin] [date] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
CREATE TABLE [dbo].[professeur](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](50) NOT NULL,
	[LastName] [nvarchar](50) NOT NULL,
	[Phone] [nvarchar](20) NOT NULL,
	[Email] [nvarchar](50) NOT NULL,
	[DOB] [date]  NULL,
	[UE_ID] [int]  FOREIGN KEY (UE_ID) REFERENCES uE (ID),
	[SessionUE_ID] [int]  FOREIGN KEY (SessionUE_ID) REFERENCES sessionUE (ID),
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[secteur](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Intitule] [nvarchar](50) NOT NULL,
	[DateDebut] [date] NOT NULL,
	[DateFin] [date] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
CREATE TABLE [dbo].[section](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Debouches] [nvarchar](50) NOT NULL,
	[Description] [nvarchar](50) NOT NULL,
	[ImageSection] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]



CREATE TABLE [dbo].[secteur_section](
[ID] [int] IDENTITY(1,1) NOT NULL,
	[SECTEUR_ID] [int]   FOREIGN KEY (SECTEUR_ID) REFERENCES secteur (ID),
	[SECTiON_ID] [int]   FOREIGN KEY (SECTiON_ID) REFERENCES section (ID),
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
CREATE TABLE [dbo].[section_ue](
[ID] [int] IDENTITY(1,1) NOT NULL,
	[SECTION_ID] [int] FOREIGN KEY (SECTION_ID) REFERENCES secteur (ID),
	[UE_ID] [int] FOREIGN KEY (UE_ID) REFERENCES Ue (ID),
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
CREATE TABLE [dbo].[sessionUE_Section](
[ID] [int] IDENTITY(1,1) NOT NULL,
	[SESSIONUE_ID] [int] FOREIGN KEY (SESSIONUE_ID) REFERENCES sessionUE (ID),
     [SECTION_ID] [int] FOREIGN KEY (SECTION_ID) REFERENCES secteur (ID),
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]