//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SitewebModel", "FK_SESSIONUE_PROFESSEUR", "PROFESSEUR", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(webschool.PROFESSEUR), "SESSIONUE", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(webschool.SESSIONUE), true)]
[assembly: EdmRelationshipAttribute("SitewebModel", "FK_SECTION_SECTEUR", "SECTEUR", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(webschool.SECTEUR), "SECTION", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(webschool.SECTION), true)]
[assembly: EdmRelationshipAttribute("SitewebModel", "FK_UE_SECTION", "SECTION", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(webschool.SECTION), "UE", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(webschool.UE), true)]
[assembly: EdmRelationshipAttribute("SitewebModel", "FK_SESSIONUE_UE", "UE", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(webschool.UE), "SESSIONUE", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(webschool.SESSIONUE), true)]
[assembly: EdmRelationshipAttribute("SitewebModel", "DEBOUCHER", "METIER", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(webschool.METIER), "SECTION", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(webschool.SECTION))]
[assembly: EdmRelationshipAttribute("SitewebModel", "LOCALISER", "LOCAL", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(webschool.LOCAL), "SESSIONUE", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(webschool.SESSIONUE))]

#endregion

namespace webschool
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SitewebEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SitewebEntities object using the connection string found in the 'SitewebEntities' section of the application configuration file.
        /// </summary>
        public SitewebEntities() : base("name=SitewebEntities", "SitewebEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SitewebEntities object.
        /// </summary>
        public SitewebEntities(string connectionString) : base(connectionString, "SitewebEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SitewebEntities object.
        /// </summary>
        public SitewebEntities(EntityConnection connection) : base(connection, "SitewebEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LOCAL> LOCALs
        {
            get
            {
                if ((_LOCALs == null))
                {
                    _LOCALs = base.CreateObjectSet<LOCAL>("LOCALs");
                }
                return _LOCALs;
            }
        }
        private ObjectSet<LOCAL> _LOCALs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<METIER> METIERs
        {
            get
            {
                if ((_METIERs == null))
                {
                    _METIERs = base.CreateObjectSet<METIER>("METIERs");
                }
                return _METIERs;
            }
        }
        private ObjectSet<METIER> _METIERs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PROFESSEUR> PROFESSEURs
        {
            get
            {
                if ((_PROFESSEURs == null))
                {
                    _PROFESSEURs = base.CreateObjectSet<PROFESSEUR>("PROFESSEURs");
                }
                return _PROFESSEURs;
            }
        }
        private ObjectSet<PROFESSEUR> _PROFESSEURs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SECTEUR> SECTEURs
        {
            get
            {
                if ((_SECTEURs == null))
                {
                    _SECTEURs = base.CreateObjectSet<SECTEUR>("SECTEURs");
                }
                return _SECTEURs;
            }
        }
        private ObjectSet<SECTEUR> _SECTEURs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SECTION> SECTIONs
        {
            get
            {
                if ((_SECTIONs == null))
                {
                    _SECTIONs = base.CreateObjectSet<SECTION>("SECTIONs");
                }
                return _SECTIONs;
            }
        }
        private ObjectSet<SECTION> _SECTIONs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SESSIONUE> SESSIONUEs
        {
            get
            {
                if ((_SESSIONUEs == null))
                {
                    _SESSIONUEs = base.CreateObjectSet<SESSIONUE>("SESSIONUEs");
                }
                return _SESSIONUEs;
            }
        }
        private ObjectSet<SESSIONUE> _SESSIONUEs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UE> UEs
        {
            get
            {
                if ((_UEs == null))
                {
                    _UEs = base.CreateObjectSet<UE>("UEs");
                }
                return _UEs;
            }
        }
        private ObjectSet<UE> _UEs;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LOCALs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLOCALs(LOCAL lOCAL)
        {
            base.AddObject("LOCALs", lOCAL);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the METIERs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMETIERs(METIER mETIER)
        {
            base.AddObject("METIERs", mETIER);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PROFESSEURs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPROFESSEURs(PROFESSEUR pROFESSEUR)
        {
            base.AddObject("PROFESSEURs", pROFESSEUR);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SECTEURs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSECTEURs(SECTEUR sECTEUR)
        {
            base.AddObject("SECTEURs", sECTEUR);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SECTIONs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSECTIONs(SECTION sECTION)
        {
            base.AddObject("SECTIONs", sECTION);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SESSIONUEs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSESSIONUEs(SESSIONUE sESSIONUE)
        {
            base.AddObject("SESSIONUEs", sESSIONUE);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UEs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUEs(UE uE)
        {
            base.AddObject("UEs", uE);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SitewebModel", Name="LOCAL")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LOCAL : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LOCAL object.
        /// </summary>
        /// <param name="iDLOCAL">Initial value of the IDLOCAL property.</param>
        /// <param name="lIEU">Initial value of the LIEU property.</param>
        public static LOCAL CreateLOCAL(global::System.Int32 iDLOCAL, global::System.String lIEU)
        {
            LOCAL lOCAL = new LOCAL();
            lOCAL.IDLOCAL = iDLOCAL;
            lOCAL.LIEU = lIEU;
            return lOCAL;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDLOCAL
        {
            get
            {
                return _IDLOCAL;
            }
            set
            {
                if (_IDLOCAL != value)
                {
                    OnIDLOCALChanging(value);
                    ReportPropertyChanging("IDLOCAL");
                    _IDLOCAL = StructuralObject.SetValidValue(value, "IDLOCAL");
                    ReportPropertyChanged("IDLOCAL");
                    OnIDLOCALChanged();
                }
            }
        }
        private global::System.Int32 _IDLOCAL;
        partial void OnIDLOCALChanging(global::System.Int32 value);
        partial void OnIDLOCALChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LIEU
        {
            get
            {
                return _LIEU;
            }
            set
            {
                OnLIEUChanging(value);
                ReportPropertyChanging("LIEU");
                _LIEU = StructuralObject.SetValidValue(value, false, "LIEU");
                ReportPropertyChanged("LIEU");
                OnLIEUChanged();
            }
        }
        private global::System.String _LIEU;
        partial void OnLIEUChanging(global::System.String value);
        partial void OnLIEUChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SitewebModel", "LOCALISER", "SESSIONUE")]
        public EntityCollection<SESSIONUE> SESSIONUEs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SESSIONUE>("SitewebModel.LOCALISER", "SESSIONUE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SESSIONUE>("SitewebModel.LOCALISER", "SESSIONUE", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SitewebModel", Name="METIER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class METIER : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new METIER object.
        /// </summary>
        /// <param name="iDMETIER">Initial value of the IDMETIER property.</param>
        /// <param name="dESCRIPTION">Initial value of the DESCRIPTION property.</param>
        public static METIER CreateMETIER(global::System.Int32 iDMETIER, global::System.String dESCRIPTION)
        {
            METIER mETIER = new METIER();
            mETIER.IDMETIER = iDMETIER;
            mETIER.DESCRIPTION = dESCRIPTION;
            return mETIER;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDMETIER
        {
            get
            {
                return _IDMETIER;
            }
            set
            {
                if (_IDMETIER != value)
                {
                    OnIDMETIERChanging(value);
                    ReportPropertyChanging("IDMETIER");
                    _IDMETIER = StructuralObject.SetValidValue(value, "IDMETIER");
                    ReportPropertyChanged("IDMETIER");
                    OnIDMETIERChanged();
                }
            }
        }
        private global::System.Int32 _IDMETIER;
        partial void OnIDMETIERChanging(global::System.Int32 value);
        partial void OnIDMETIERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DESCRIPTION
        {
            get
            {
                return _DESCRIPTION;
            }
            set
            {
                OnDESCRIPTIONChanging(value);
                ReportPropertyChanging("DESCRIPTION");
                _DESCRIPTION = StructuralObject.SetValidValue(value, false, "DESCRIPTION");
                ReportPropertyChanged("DESCRIPTION");
                OnDESCRIPTIONChanged();
            }
        }
        private global::System.String _DESCRIPTION;
        partial void OnDESCRIPTIONChanging(global::System.String value);
        partial void OnDESCRIPTIONChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SitewebModel", "DEBOUCHER", "SECTION")]
        public EntityCollection<SECTION> SECTIONs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SECTION>("SitewebModel.DEBOUCHER", "SECTION");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SECTION>("SitewebModel.DEBOUCHER", "SECTION", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SitewebModel", Name="PROFESSEUR")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PROFESSEUR : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PROFESSEUR object.
        /// </summary>
        /// <param name="iDPROFESSEUR">Initial value of the IDPROFESSEUR property.</param>
        /// <param name="nOM">Initial value of the NOM property.</param>
        /// <param name="pRENOM">Initial value of the PRENOM property.</param>
        /// <param name="tELEPHONE">Initial value of the TELEPHONE property.</param>
        /// <param name="eMAIL">Initial value of the EMAIL property.</param>
        public static PROFESSEUR CreatePROFESSEUR(global::System.Int32 iDPROFESSEUR, global::System.String nOM, global::System.String pRENOM, global::System.Int32 tELEPHONE, global::System.String eMAIL)
        {
            PROFESSEUR pROFESSEUR = new PROFESSEUR();
            pROFESSEUR.IDPROFESSEUR = iDPROFESSEUR;
            pROFESSEUR.NOM = nOM;
            pROFESSEUR.PRENOM = pRENOM;
            pROFESSEUR.TELEPHONE = tELEPHONE;
            pROFESSEUR.EMAIL = eMAIL;
            return pROFESSEUR;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDPROFESSEUR
        {
            get
            {
                return _IDPROFESSEUR;
            }
            set
            {
                if (_IDPROFESSEUR != value)
                {
                    OnIDPROFESSEURChanging(value);
                    ReportPropertyChanging("IDPROFESSEUR");
                    _IDPROFESSEUR = StructuralObject.SetValidValue(value, "IDPROFESSEUR");
                    ReportPropertyChanged("IDPROFESSEUR");
                    OnIDPROFESSEURChanged();
                }
            }
        }
        private global::System.Int32 _IDPROFESSEUR;
        partial void OnIDPROFESSEURChanging(global::System.Int32 value);
        partial void OnIDPROFESSEURChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOM
        {
            get
            {
                return _NOM;
            }
            set
            {
                OnNOMChanging(value);
                ReportPropertyChanging("NOM");
                _NOM = StructuralObject.SetValidValue(value, false, "NOM");
                ReportPropertyChanged("NOM");
                OnNOMChanged();
            }
        }
        private global::System.String _NOM;
        partial void OnNOMChanging(global::System.String value);
        partial void OnNOMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PRENOM
        {
            get
            {
                return _PRENOM;
            }
            set
            {
                OnPRENOMChanging(value);
                ReportPropertyChanging("PRENOM");
                _PRENOM = StructuralObject.SetValidValue(value, false, "PRENOM");
                ReportPropertyChanged("PRENOM");
                OnPRENOMChanged();
            }
        }
        private global::System.String _PRENOM;
        partial void OnPRENOMChanging(global::System.String value);
        partial void OnPRENOMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TELEPHONE
        {
            get
            {
                return _TELEPHONE;
            }
            set
            {
                OnTELEPHONEChanging(value);
                ReportPropertyChanging("TELEPHONE");
                _TELEPHONE = StructuralObject.SetValidValue(value, "TELEPHONE");
                ReportPropertyChanged("TELEPHONE");
                OnTELEPHONEChanged();
            }
        }
        private global::System.Int32 _TELEPHONE;
        partial void OnTELEPHONEChanging(global::System.Int32 value);
        partial void OnTELEPHONEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EMAIL
        {
            get
            {
                return _EMAIL;
            }
            set
            {
                OnEMAILChanging(value);
                ReportPropertyChanging("EMAIL");
                _EMAIL = StructuralObject.SetValidValue(value, false, "EMAIL");
                ReportPropertyChanged("EMAIL");
                OnEMAILChanged();
            }
        }
        private global::System.String _EMAIL;
        partial void OnEMAILChanging(global::System.String value);
        partial void OnEMAILChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SitewebModel", "FK_SESSIONUE_PROFESSEUR", "SESSIONUE")]
        public EntityCollection<SESSIONUE> SESSIONUEs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SESSIONUE>("SitewebModel.FK_SESSIONUE_PROFESSEUR", "SESSIONUE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SESSIONUE>("SitewebModel.FK_SESSIONUE_PROFESSEUR", "SESSIONUE", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SitewebModel", Name="SECTEUR")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SECTEUR : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SECTEUR object.
        /// </summary>
        /// <param name="iDSECTEUR">Initial value of the IDSECTEUR property.</param>
        /// <param name="iNTITULE">Initial value of the INTITULE property.</param>
        /// <param name="dATEDEBUT">Initial value of the DATEDEBUT property.</param>
        /// <param name="dATEFIN">Initial value of the DATEFIN property.</param>
        public static SECTEUR CreateSECTEUR(global::System.Int32 iDSECTEUR, global::System.String iNTITULE, global::System.DateTime dATEDEBUT, global::System.DateTime dATEFIN)
        {
            SECTEUR sECTEUR = new SECTEUR();
            sECTEUR.IDSECTEUR = iDSECTEUR;
            sECTEUR.INTITULE = iNTITULE;
            sECTEUR.DATEDEBUT = dATEDEBUT;
            sECTEUR.DATEFIN = dATEFIN;
            return sECTEUR;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDSECTEUR
        {
            get
            {
                return _IDSECTEUR;
            }
            set
            {
                if (_IDSECTEUR != value)
                {
                    OnIDSECTEURChanging(value);
                    ReportPropertyChanging("IDSECTEUR");
                    _IDSECTEUR = StructuralObject.SetValidValue(value, "IDSECTEUR");
                    ReportPropertyChanged("IDSECTEUR");
                    OnIDSECTEURChanged();
                }
            }
        }
        private global::System.Int32 _IDSECTEUR;
        partial void OnIDSECTEURChanging(global::System.Int32 value);
        partial void OnIDSECTEURChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String INTITULE
        {
            get
            {
                return _INTITULE;
            }
            set
            {
                OnINTITULEChanging(value);
                ReportPropertyChanging("INTITULE");
                _INTITULE = StructuralObject.SetValidValue(value, false, "INTITULE");
                ReportPropertyChanged("INTITULE");
                OnINTITULEChanged();
            }
        }
        private global::System.String _INTITULE;
        partial void OnINTITULEChanging(global::System.String value);
        partial void OnINTITULEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DATEDEBUT
        {
            get
            {
                return _DATEDEBUT;
            }
            set
            {
                OnDATEDEBUTChanging(value);
                ReportPropertyChanging("DATEDEBUT");
                _DATEDEBUT = StructuralObject.SetValidValue(value, "DATEDEBUT");
                ReportPropertyChanged("DATEDEBUT");
                OnDATEDEBUTChanged();
            }
        }
        private global::System.DateTime _DATEDEBUT;
        partial void OnDATEDEBUTChanging(global::System.DateTime value);
        partial void OnDATEDEBUTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DATEFIN
        {
            get
            {
                return _DATEFIN;
            }
            set
            {
                OnDATEFINChanging(value);
                ReportPropertyChanging("DATEFIN");
                _DATEFIN = StructuralObject.SetValidValue(value, "DATEFIN");
                ReportPropertyChanged("DATEFIN");
                OnDATEFINChanged();
            }
        }
        private global::System.DateTime _DATEFIN;
        partial void OnDATEFINChanging(global::System.DateTime value);
        partial void OnDATEFINChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SitewebModel", "FK_SECTION_SECTEUR", "SECTION")]
        public EntityCollection<SECTION> SECTIONs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SECTION>("SitewebModel.FK_SECTION_SECTEUR", "SECTION");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SECTION>("SitewebModel.FK_SECTION_SECTEUR", "SECTION", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SitewebModel", Name="SECTION")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SECTION : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SECTION object.
        /// </summary>
        /// <param name="iDSECTION">Initial value of the IDSECTION property.</param>
        /// <param name="iDSECTEUR">Initial value of the IDSECTEUR property.</param>
        /// <param name="dESCRIPTION">Initial value of the DESCRIPTION property.</param>
        /// <param name="iMAGESECTION">Initial value of the IMAGESECTION property.</param>
        public static SECTION CreateSECTION(global::System.Int32 iDSECTION, global::System.Int32 iDSECTEUR, global::System.String dESCRIPTION, global::System.String iMAGESECTION)
        {
            SECTION sECTION = new SECTION();
            sECTION.IDSECTION = iDSECTION;
            sECTION.IDSECTEUR = iDSECTEUR;
            sECTION.DESCRIPTION = dESCRIPTION;
            sECTION.IMAGESECTION = iMAGESECTION;
            return sECTION;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDSECTION
        {
            get
            {
                return _IDSECTION;
            }
            set
            {
                if (_IDSECTION != value)
                {
                    OnIDSECTIONChanging(value);
                    ReportPropertyChanging("IDSECTION");
                    _IDSECTION = StructuralObject.SetValidValue(value, "IDSECTION");
                    ReportPropertyChanged("IDSECTION");
                    OnIDSECTIONChanged();
                }
            }
        }
        private global::System.Int32 _IDSECTION;
        partial void OnIDSECTIONChanging(global::System.Int32 value);
        partial void OnIDSECTIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDSECTEUR
        {
            get
            {
                return _IDSECTEUR;
            }
            set
            {
                OnIDSECTEURChanging(value);
                ReportPropertyChanging("IDSECTEUR");
                _IDSECTEUR = StructuralObject.SetValidValue(value, "IDSECTEUR");
                ReportPropertyChanged("IDSECTEUR");
                OnIDSECTEURChanged();
            }
        }
        private global::System.Int32 _IDSECTEUR;
        partial void OnIDSECTEURChanging(global::System.Int32 value);
        partial void OnIDSECTEURChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DESCRIPTION
        {
            get
            {
                return _DESCRIPTION;
            }
            set
            {
                OnDESCRIPTIONChanging(value);
                ReportPropertyChanging("DESCRIPTION");
                _DESCRIPTION = StructuralObject.SetValidValue(value, false, "DESCRIPTION");
                ReportPropertyChanged("DESCRIPTION");
                OnDESCRIPTIONChanged();
            }
        }
        private global::System.String _DESCRIPTION;
        partial void OnDESCRIPTIONChanging(global::System.String value);
        partial void OnDESCRIPTIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IMAGESECTION
        {
            get
            {
                return _IMAGESECTION;
            }
            set
            {
                OnIMAGESECTIONChanging(value);
                ReportPropertyChanging("IMAGESECTION");
                _IMAGESECTION = StructuralObject.SetValidValue(value, false, "IMAGESECTION");
                ReportPropertyChanged("IMAGESECTION");
                OnIMAGESECTIONChanged();
            }
        }
        private global::System.String _IMAGESECTION;
        partial void OnIMAGESECTIONChanging(global::System.String value);
        partial void OnIMAGESECTIONChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SitewebModel", "FK_SECTION_SECTEUR", "SECTEUR")]
        public SECTEUR SECTEUR
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SECTEUR>("SitewebModel.FK_SECTION_SECTEUR", "SECTEUR").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SECTEUR>("SitewebModel.FK_SECTION_SECTEUR", "SECTEUR").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SECTEUR> SECTEURReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SECTEUR>("SitewebModel.FK_SECTION_SECTEUR", "SECTEUR");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SECTEUR>("SitewebModel.FK_SECTION_SECTEUR", "SECTEUR", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SitewebModel", "FK_UE_SECTION", "UE")]
        public EntityCollection<UE> UEs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UE>("SitewebModel.FK_UE_SECTION", "UE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UE>("SitewebModel.FK_UE_SECTION", "UE", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SitewebModel", "DEBOUCHER", "METIER")]
        public EntityCollection<METIER> METIERs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<METIER>("SitewebModel.DEBOUCHER", "METIER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<METIER>("SitewebModel.DEBOUCHER", "METIER", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SitewebModel", Name="SESSIONUE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SESSIONUE : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SESSIONUE object.
        /// </summary>
        /// <param name="iDSESSIONUE">Initial value of the IDSESSIONUE property.</param>
        /// <param name="dATEDEBUT">Initial value of the DATEDEBUT property.</param>
        /// <param name="dATEFIN">Initial value of the DATEFIN property.</param>
        /// <param name="pERIODE">Initial value of the PERIODE property.</param>
        /// <param name="hEUREDEBUT">Initial value of the HEUREDEBUT property.</param>
        /// <param name="hEUREFIN">Initial value of the HEUREFIN property.</param>
        public static SESSIONUE CreateSESSIONUE(global::System.Int32 iDSESSIONUE, global::System.DateTime dATEDEBUT, global::System.DateTime dATEFIN, global::System.Int32 pERIODE, global::System.TimeSpan hEUREDEBUT, global::System.TimeSpan hEUREFIN)
        {
            SESSIONUE sESSIONUE = new SESSIONUE();
            sESSIONUE.IDSESSIONUE = iDSESSIONUE;
            sESSIONUE.DATEDEBUT = dATEDEBUT;
            sESSIONUE.DATEFIN = dATEFIN;
            sESSIONUE.PERIODE = pERIODE;
            sESSIONUE.HEUREDEBUT = hEUREDEBUT;
            sESSIONUE.HEUREFIN = hEUREFIN;
            return sESSIONUE;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDSESSIONUE
        {
            get
            {
                return _IDSESSIONUE;
            }
            set
            {
                if (_IDSESSIONUE != value)
                {
                    OnIDSESSIONUEChanging(value);
                    ReportPropertyChanging("IDSESSIONUE");
                    _IDSESSIONUE = StructuralObject.SetValidValue(value, "IDSESSIONUE");
                    ReportPropertyChanged("IDSESSIONUE");
                    OnIDSESSIONUEChanged();
                }
            }
        }
        private global::System.Int32 _IDSESSIONUE;
        partial void OnIDSESSIONUEChanging(global::System.Int32 value);
        partial void OnIDSESSIONUEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDPROFESSEUR
        {
            get
            {
                return _IDPROFESSEUR;
            }
            set
            {
                OnIDPROFESSEURChanging(value);
                ReportPropertyChanging("IDPROFESSEUR");
                _IDPROFESSEUR = StructuralObject.SetValidValue(value, "IDPROFESSEUR");
                ReportPropertyChanged("IDPROFESSEUR");
                OnIDPROFESSEURChanged();
            }
        }
        private Nullable<global::System.Int32> _IDPROFESSEUR;
        partial void OnIDPROFESSEURChanging(Nullable<global::System.Int32> value);
        partial void OnIDPROFESSEURChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDUE
        {
            get
            {
                return _IDUE;
            }
            set
            {
                OnIDUEChanging(value);
                ReportPropertyChanging("IDUE");
                _IDUE = StructuralObject.SetValidValue(value, "IDUE");
                ReportPropertyChanged("IDUE");
                OnIDUEChanged();
            }
        }
        private Nullable<global::System.Int32> _IDUE;
        partial void OnIDUEChanging(Nullable<global::System.Int32> value);
        partial void OnIDUEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DATEDEBUT
        {
            get
            {
                return _DATEDEBUT;
            }
            set
            {
                OnDATEDEBUTChanging(value);
                ReportPropertyChanging("DATEDEBUT");
                _DATEDEBUT = StructuralObject.SetValidValue(value, "DATEDEBUT");
                ReportPropertyChanged("DATEDEBUT");
                OnDATEDEBUTChanged();
            }
        }
        private global::System.DateTime _DATEDEBUT;
        partial void OnDATEDEBUTChanging(global::System.DateTime value);
        partial void OnDATEDEBUTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DATEFIN
        {
            get
            {
                return _DATEFIN;
            }
            set
            {
                OnDATEFINChanging(value);
                ReportPropertyChanging("DATEFIN");
                _DATEFIN = StructuralObject.SetValidValue(value, "DATEFIN");
                ReportPropertyChanged("DATEFIN");
                OnDATEFINChanged();
            }
        }
        private global::System.DateTime _DATEFIN;
        partial void OnDATEFINChanging(global::System.DateTime value);
        partial void OnDATEFINChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PERIODE
        {
            get
            {
                return _PERIODE;
            }
            set
            {
                OnPERIODEChanging(value);
                ReportPropertyChanging("PERIODE");
                _PERIODE = StructuralObject.SetValidValue(value, "PERIODE");
                ReportPropertyChanged("PERIODE");
                OnPERIODEChanged();
            }
        }
        private global::System.Int32 _PERIODE;
        partial void OnPERIODEChanging(global::System.Int32 value);
        partial void OnPERIODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan HEUREDEBUT
        {
            get
            {
                return _HEUREDEBUT;
            }
            set
            {
                OnHEUREDEBUTChanging(value);
                ReportPropertyChanging("HEUREDEBUT");
                _HEUREDEBUT = StructuralObject.SetValidValue(value, "HEUREDEBUT");
                ReportPropertyChanged("HEUREDEBUT");
                OnHEUREDEBUTChanged();
            }
        }
        private global::System.TimeSpan _HEUREDEBUT;
        partial void OnHEUREDEBUTChanging(global::System.TimeSpan value);
        partial void OnHEUREDEBUTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan HEUREFIN
        {
            get
            {
                return _HEUREFIN;
            }
            set
            {
                OnHEUREFINChanging(value);
                ReportPropertyChanging("HEUREFIN");
                _HEUREFIN = StructuralObject.SetValidValue(value, "HEUREFIN");
                ReportPropertyChanged("HEUREFIN");
                OnHEUREFINChanged();
            }
        }
        private global::System.TimeSpan _HEUREFIN;
        partial void OnHEUREFINChanging(global::System.TimeSpan value);
        partial void OnHEUREFINChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SitewebModel", "FK_SESSIONUE_PROFESSEUR", "PROFESSEUR")]
        public PROFESSEUR PROFESSEUR
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PROFESSEUR>("SitewebModel.FK_SESSIONUE_PROFESSEUR", "PROFESSEUR").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PROFESSEUR>("SitewebModel.FK_SESSIONUE_PROFESSEUR", "PROFESSEUR").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PROFESSEUR> PROFESSEURReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PROFESSEUR>("SitewebModel.FK_SESSIONUE_PROFESSEUR", "PROFESSEUR");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PROFESSEUR>("SitewebModel.FK_SESSIONUE_PROFESSEUR", "PROFESSEUR", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SitewebModel", "FK_SESSIONUE_UE", "UE")]
        public UE UE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UE>("SitewebModel.FK_SESSIONUE_UE", "UE").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UE>("SitewebModel.FK_SESSIONUE_UE", "UE").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UE> UEReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UE>("SitewebModel.FK_SESSIONUE_UE", "UE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UE>("SitewebModel.FK_SESSIONUE_UE", "UE", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SitewebModel", "LOCALISER", "LOCAL")]
        public EntityCollection<LOCAL> LOCALs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<LOCAL>("SitewebModel.LOCALISER", "LOCAL");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<LOCAL>("SitewebModel.LOCALISER", "LOCAL", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SitewebModel", Name="UE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UE : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UE object.
        /// </summary>
        /// <param name="iDUE">Initial value of the IDUE property.</param>
        /// <param name="tITRE">Initial value of the TITRE property.</param>
        /// <param name="dESCRIPTION">Initial value of the DESCRIPTION property.</param>
        /// <param name="pERIODE">Initial value of the PERIODE property.</param>
        /// <param name="eCTS">Initial value of the ECTS property.</param>
        public static UE CreateUE(global::System.Int32 iDUE, global::System.String tITRE, global::System.String dESCRIPTION, global::System.Int32 pERIODE, global::System.Int32 eCTS)
        {
            UE uE = new UE();
            uE.IDUE = iDUE;
            uE.TITRE = tITRE;
            uE.DESCRIPTION = dESCRIPTION;
            uE.PERIODE = pERIODE;
            uE.ECTS = eCTS;
            return uE;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDUE
        {
            get
            {
                return _IDUE;
            }
            set
            {
                if (_IDUE != value)
                {
                    OnIDUEChanging(value);
                    ReportPropertyChanging("IDUE");
                    _IDUE = StructuralObject.SetValidValue(value, "IDUE");
                    ReportPropertyChanged("IDUE");
                    OnIDUEChanged();
                }
            }
        }
        private global::System.Int32 _IDUE;
        partial void OnIDUEChanging(global::System.Int32 value);
        partial void OnIDUEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDSECTION
        {
            get
            {
                return _IDSECTION;
            }
            set
            {
                OnIDSECTIONChanging(value);
                ReportPropertyChanging("IDSECTION");
                _IDSECTION = StructuralObject.SetValidValue(value, "IDSECTION");
                ReportPropertyChanged("IDSECTION");
                OnIDSECTIONChanged();
            }
        }
        private Nullable<global::System.Int32> _IDSECTION;
        partial void OnIDSECTIONChanging(Nullable<global::System.Int32> value);
        partial void OnIDSECTIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TITRE
        {
            get
            {
                return _TITRE;
            }
            set
            {
                OnTITREChanging(value);
                ReportPropertyChanging("TITRE");
                _TITRE = StructuralObject.SetValidValue(value, false, "TITRE");
                ReportPropertyChanged("TITRE");
                OnTITREChanged();
            }
        }
        private global::System.String _TITRE;
        partial void OnTITREChanging(global::System.String value);
        partial void OnTITREChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DESCRIPTION
        {
            get
            {
                return _DESCRIPTION;
            }
            set
            {
                OnDESCRIPTIONChanging(value);
                ReportPropertyChanging("DESCRIPTION");
                _DESCRIPTION = StructuralObject.SetValidValue(value, false, "DESCRIPTION");
                ReportPropertyChanged("DESCRIPTION");
                OnDESCRIPTIONChanged();
            }
        }
        private global::System.String _DESCRIPTION;
        partial void OnDESCRIPTIONChanging(global::System.String value);
        partial void OnDESCRIPTIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PERIODE
        {
            get
            {
                return _PERIODE;
            }
            set
            {
                OnPERIODEChanging(value);
                ReportPropertyChanging("PERIODE");
                _PERIODE = StructuralObject.SetValidValue(value, "PERIODE");
                ReportPropertyChanged("PERIODE");
                OnPERIODEChanged();
            }
        }
        private global::System.Int32 _PERIODE;
        partial void OnPERIODEChanging(global::System.Int32 value);
        partial void OnPERIODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ECTS
        {
            get
            {
                return _ECTS;
            }
            set
            {
                OnECTSChanging(value);
                ReportPropertyChanging("ECTS");
                _ECTS = StructuralObject.SetValidValue(value, "ECTS");
                ReportPropertyChanged("ECTS");
                OnECTSChanged();
            }
        }
        private global::System.Int32 _ECTS;
        partial void OnECTSChanging(global::System.Int32 value);
        partial void OnECTSChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SitewebModel", "FK_UE_SECTION", "SECTION")]
        public SECTION SECTION
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SECTION>("SitewebModel.FK_UE_SECTION", "SECTION").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SECTION>("SitewebModel.FK_UE_SECTION", "SECTION").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SECTION> SECTIONReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SECTION>("SitewebModel.FK_UE_SECTION", "SECTION");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SECTION>("SitewebModel.FK_UE_SECTION", "SECTION", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SitewebModel", "FK_SESSIONUE_UE", "SESSIONUE")]
        public EntityCollection<SESSIONUE> SESSIONUEs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SESSIONUE>("SitewebModel.FK_SESSIONUE_UE", "SESSIONUE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SESSIONUE>("SitewebModel.FK_SESSIONUE_UE", "SESSIONUE", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
